name: pull_request_check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 

      - name: Print course name
        env:
          COURSE_NAME : CSYE6225

        run:
          echo $COURSE_NAME 

